### ISSUE TITLE
Characters transposed in some cases

### ISSUE THREAD

**Issue by EFH52** [thompson-vii/kb16_rev2_vial_fw#14]
`C:\Users\eric\Go`
is in the macro as a string of text.
Sometimes:
`C:\Userse\ric\Go` or `C:\User\sericf\Go`
Also
`|` replaces `\` or `;` replaces `:`
So the shift keys bounces around as well.

It doesn't do this all the time, but maybe 10% of the time things error out.

Excecuted macro.
`[["down", "KC_LGUI"], ["tap", "KC_R"], ["up", "KC_LGUI"], ["delay", 15], ["text", "C:\\Users\\eric\\Google Drive\\SystemCommons\\Documents\\Python Scripts\\Python Scripts.code-workspace"], ["tap", "KC_ENTER"]]`

**Comment by thompson-vii** [comment]
Vial offer no delay for the text items. Not much i can do here. I'd use 
a auto hotkey script instead.

example in my script

```ahk

f21::
Run, C:\Program Files\Krita (x64)\bin\krita.exe
return

```

and add that script to startup
