### ISSUE TITLE
Awesome!  How do implement for other macropads?

### ISSUE THREAD

**Issue by jenny787** [thompson-vii/kb16_rev2_vial_fw#6]
This is a great repo, well done!!  I'm trying to follow what you did.  How can this be done for the other DOIO macropads?  I have them all, and want to do it on the 38% macropad .  Where did you get that kb16 original file?  Is that the key?

**Comment by thompson-vii** [comment]
The pad has to be ported to mainline qmk first. I used HorrorTroll's 
port which is in the qmk repo. People have been asked for the source 
code but Chinese manufacturers prefer you to use the precompiled 
firmware instead. You will have to reverse engineer the pin out and 
write the qmk code yourself or have someone else to do it.

**Comment by jenny787** [comment]
OK thank you.  Yes I hate that sideload business.  I love what you did.  I'll ask HorrorTroll if he has it on his radar.  I could donate one to him if needed.
