### ISSUE TITLE
Include the actual code used in compiling the bin

### ISSUE THREAD

**Issue by Sett17** [thompson-vii/kb16_rev2_vial_fw#7]
Is it possible for you to include all the actual code (all the stuff to do with this kb, I don't mean the whole of QMK) you used when compiling the firmware?

As I understand this is mostly just kind of default code included in 40d07283944b3f77a6bd671c4147a29dbb956deb.

**Comment by thompson-vii** [comment]
Everything you need to compile the firmware is under rev2

**Comment by Sett17** [comment]
But is the code in rev2 the same that you used to compile the bin?
